### ISSUE TITLE
Passing Midi data through without Callbacks

### ISSUE THREAD

**Issue by jhsa** [thomasgeissl/ESP-NOW-MIDI#13]
Hi Thomas, thanks a lot for your work on ESP-NOW MIDI. This is great as BLE has been a big headache lately, specially setting up a client. 
Anyway, I think I am going to try your library on my little project. I cannot find any discussion pages or forums where I could ask questions so I will post here. Please delete if you find this inappropriate, and point me to somewhere else where we can discuss the library and also ask for help. 
I can see you are using callbacks to handle the midi messages. But what about just passing the raw data through from USB to wireless and vice-versa in case we just want a midi adapter/converter? And why not also add some Serial Midi? This would cover all flavors of Midi.
I consider myself a beginner as far as coding is concerned, and I apologize if I am writing nonsense here.
One of the advantages of routing the data without callbacks would be reduced latency?
If this is already possible, and in a bidirectional way, would you mind writing a simple example for us poor slow learners? ;) 

Thank you so much.

**Comment by thomasgeissl** [comment]
hey hey, no worries, here is good place to ask questions.

the dongle example, is basically a esp now midi interface to your laptop (or any other usb midi host). it will listen to midi messages via usb midi from your laptop and sends it via esp now to all connected peers. and it will receive esp now messages from the peers and sends it via usb midi to your laptop.

you could write a firmware that is a usb host and read midi from a connected midi controller.
or even read midi from a 5pin serial midi connector. 

i havent dont measurements, still on the list. but i dont think the callback api is much of an overhead.

if you wanna give it a try, e.g. reading serial midi and send it via esp now midi to a dongle.

this is untested, but might help as a starting point


```
#include "esp_now_midi.h"
#include <MIDI.h> // https://github.com/FortySevenEffects/arduino_midi_library

// Create a new instance of the library using Serial1
MIDI_CREATE_INSTANCE(HardwareSerial, Serial1, MIDI);

uint8_t peerMacAddress[6] = {0xCC, 0x8D, 0xA2, 0x8B, 0x85, 0x1C};

void customOnDataSent(const uint8_t *mac_addr, esp_now_send_status_t status)
{
  // Serial.print("Custom Callback - Status: ");
  // Serial.println(status == ESP_NOW_SEND_SUCCESS ? "Success" : "Failure");
}

void setup() {
  Serial.begin(115200);
  Serial1.begin(31250); // MIDI baud rate

  MIDI.begin(MIDI_CHANNEL_OMNI); // Listen to all MIDI channels
  Serial.println("MIDI Ready");

  WiFi.mode(WIFI_STA);
  ESP_NOW_MIDI.setup(peerMacAddress, customOnDataSent);
  // ESP_NOW_MIDI.setup(destinationMacAddress); //or get rid of the custom send function and use the default one

}

void loop() {
  if (MIDI.read()) {
    byte type = MIDI.getType();
    byte channel = MIDI.getChannel();
    byte data1 = MIDI.getData1();
    byte data2 = MIDI.getData2();

    Serial.print("MIDI message: ");
    Serial.print(type);
    Serial.print(", Channel: ");
    Serial.print(channel);
    Serial.print(", Data1: ");
    Serial.print(data1);
    Serial.print(", Data2: ");
    Serial.println(data2);

    switch(type){
       case 0x90: ESP_NOW_MIDI.sendNoteOn(data1, data2, 1); break;
       case 0x80: ESP_NOW_MIDI.sendNoteOff(data1, data2, 1); break;
    }
  }
}

```

**Comment by jhsa** [comment]
Thank you Thomas, I have been digging into the ESP-NOW code, and reading about it to understand its basics.
My problem is, on my project I cannot decide what is going to be a sender and what is going to be a dongle :) 
My project is a guitar effect's pedal controller that also sends and receives midi, currently via serial midi, USB Midi, and MIDI BLE (Bluetooth). I need a an external device that communicates with it wirelessly  (Your Dongle code?), and via serial midi with my pedalboard. So, I am inclined to use my pedal controller as a sender and the external device as Dongle (receiver) to handle all connections. I could perhaps add other Senders connected to the Dongle and share it with all the others? That would be fantastic.
Thank you again for your patience and help..
João

EDIT: I could probably insert the Dongle's mac address on my controller's code via the "WifiManager" library.

**Comment by jhsa** [comment]
Sure, For the Dongle I had in mind something like this. I thought I could replace the BLE MIDI code with your Dongle code.
As I have mentioned on my first post, the midi library has some nice ways of handling the data and one of them is the direct use of the  .getType(), .getData1(), .getData2(), and .getChannel() functions as you can see in the code below.
I see that you use something very similar on the Dongle code, but is there any chance we could use these functions instead? I think they could save a few lines of code and make it smaller?
I hope I am not saying something stupid here..
For my controller, I think I will use the sender example as it is very similar to the way I handle the rest of the midi. I believe it would be easy to implement. 
By the way, I have just tested the Dongle code (ESP32-S3 board) and the Sender code (ESP32-S3-Zero Board), and it works. I see the received messages in the dongle on my PC's Midi App, and I send also midi to the Zero and see them on the serial monitor. Very nice indeed. Will mod the Zero's antenna for more range as I did with the other S3 board. :) 
Thank you so much for your help..



```
#include <Arduino.h>
#include "WiFiManager.h" // https://github.com/tzapu/WiFiManager
#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiUdp.h>
#include <MIDI.h>
#include <Adafruit_TinyUSB.h>
#include "BLEMIDI_Transport.h"
#include "BLEMIDI_Client_ESP32.h"

//#include <hardware/BLEMIDI_ESP32_NimBLE.h>
//#include <hardware/BLEMIDI_ESP32.h>
//#include <hardware/BLEMIDI_nRF52.h>
//#include <hardware/BLEMIDI_ArduinoBLE.h>

WiFiManager wm;

BLEMIDI_CREATE_DEFAULT_INSTANCE(); //Connect to first server found
MIDI_CREATE_INSTANCE(HardwareSerial, Serial,  MidiSerial);

//BLEMIDI_CREATE_INSTANCE("",MIDI)                  //Connect to the first server found
//BLEMIDI_CREATE_INSTANCE("f2:c1:d9:36:e7:6b",MIDI) //Connect to a specific BLE address server
//BLEMIDI_CREATE_INSTANCE("MyBLEserver",MIDI)       //Connect to a specific name server

// USB MIDI object
Adafruit_USBD_MIDI usb_midi;

// Create a new instance of the Arduino MIDI Library,
// and attach usb_midi as the transport.
MIDI_CREATE_INSTANCE(Adafruit_USBD_MIDI, usb_midi, MidiUsb);

byte Switch = 40;
int Led = 42; //modify for match with yout board
int MidiPwr = 41;
int timeout = 200;
bool isConnected = false;

/**
   -----------------------------------------------------------------------------
   When BLE is connected, LED will turn on (indicating that connection was successful)
   When receiving a NoteOn, LED will go out, on NoteOff, light comes back on.
   This is an easy and conveniant way to show that the connection is alive and working.
   -----------------------------------------------------------------------------
*/
void setup()
{
WiFiManager wm;

  BLEMIDI.setHandleConnected([]()
  {
    //    Serial.println("---------CONNECTED---------");
    isConnected = true;
    digitalWrite(Led, HIGH);
  });

  BLEMIDI.setHandleDisconnected([]()
  {
    //    Serial.println("---------NOT CONNECTED---------");
    isConnected = false;
    digitalWrite(Led, LOW);

  });

  pinMode(Led, OUTPUT);
  digitalWrite(Led, LOW);
pinMode(MidiPwr, OUTPUT);
  digitalWrite(MidiPwr, LOW);

   pinMode(Switch, INPUT_PULLUP);

 if (digitalRead(Switch) == LOW) Select_AP();
  
  TinyUSBDevice.setManufacturerDescriptor("My_Manufacturer");
  TinyUSBDevice.setProductDescriptor("BLE_USB_Aapter");

  // Initialize MIDI, and listen to all MIDI channels
  // This will also call usb_midi's begin()
  MidiUsb.begin(MIDI_CHANNEL_OMNI);

  //  Serial.begin(115200);
  MIDI.begin(MIDI_CHANNEL_OMNI);
  MidiSerial.begin(MIDI_CHANNEL_OMNI);

  MidiSerial.turnThruOff();
  MIDI.turnThruOff();
  MidiUsb.turnThruOff();
delay(500);
  digitalWrite(MidiPwr, HIGH);
  }

  void loop()
  {
    if (MidiSerial.read()) {

      MIDI.send(MidiSerial.getType(),
                MidiSerial.getData1(),
                MidiSerial.getData2(),
                MidiSerial.getChannel());

      MidiUsb.send(MidiSerial.getType(),
                   MidiSerial.getData1(),
                   MidiSerial.getData2(),
                   MidiSerial.getChannel());
    }
    if (MIDI.read()) {


      MidiSerial.send(MIDI.getType(),
                      MIDI.getData1(),
                      MIDI.getData2(),
                      MIDI.getChannel());


      MidiUsb.send(MIDI.getType(),
                   MIDI.getData1(),
                   MIDI.getData2(),
                   MIDI.getChannel());
    }

    if (MidiUsb.read()) {
      MIDI.send(MidiUsb.getType(),
                MidiUsb.getData1(),
                MidiUsb.getData2(),
                MidiUsb.getChannel());


      MidiSerial.send(MidiUsb.getType(),
                      MidiUsb.getData1(),
                      MidiUsb.getData2(),
                      MidiUsb.getChannel());


    }
  }

  void Select_AP(){
  boolean AP_Edit = true;
  
 while (AP_Edit) {
    WiFiManager wm;
    wm.setBreakAfterConfig(true);
    

    // set configportal timeout
    wm.setConfigPortalTimeout(timeout);
    //     wm.setConfigPortalBlocking(false);



    
    if (!wm.startConfigPortal("Flash ESP32 AP", "password")) {

      delay(3000);
      //reset and try again, or maybe put it to deep sleep
      
      //      WirelessType = 0;
      //      AP_Configured = false;
      AP_Edit = false;
      //      ESP.restart();

    }

    else {
      wm.disconnect();
     
      AP_Edit = false;
      //      ESP.restart();
    }

  }
}
```

**Comment by jhsa** [comment]
I have found a little mistake on the Dongle code. Both switch case  send "MIDI.sendStart();" but the second one should send "MIDI.sendStop();"

```
case MIDI_START:
      {
        MIDI.sendStart();
        break;
      }
    case MIDI_STOP:
      {
        MIDI.sendStart();
        break;
      }
```

**Comment by thomasgeissl** [comment]
thanks for finding that bug, should be fixed now on main.

sorry, i was not clear. what would help me is a kinda diagram of what you have in mind.

**Comment by jhsa** [comment]
Ok I will do that. But today is a bit complicated to do it. The concept is quite simple. at the moment I am just testing the library and I gotta say, I am really liking it to the point that even if BT starts working again, I will still implement it in my project. I did a range test between an ESP32-S3 DevKit board and a small ESP32-S2-Zero board, and the range was really good. I can imagine the improvement after I do the antenna mod on both boards.
But basically, what I am thinking to do is to use the Dongle (receiver) as  some kind of Midi Router, that perhaps connects to multiple Senders (Transmitters) that also have Midi serial and Midi USB inputs. One of these senders will be my Guitar effects pedal's Switcher, which is the project I want to update with ESP-NOW MIDI.
But I will do a Diagram later when I have more time. 
The midi code/handling I use on my pedal switcher is very similar to your "Sender" code as it also uses the same Midi library.

Another question. Your Dongle does not use the midi library to receive the data from the senders. Isn't  possible for it to also use the Midi library? As I said before all this is quite new for me, but I am a fast learner. :) 
Thank you again for all Thomas. This is brilliant..

**Comment by thomasgeissl** [comment]
please downgrade for now. i will fix it in august.
this requires some ifdefs checking board version, so i can keep it backwards compatible.

**Comment by thomasgeissl** [comment]
on the client side, any midi message on any channel is fine to register at the dongle.
i usually send cc channel 16, controller 127, value 127. but any other message would do as well

on the dongle you can manually add mac addresses, but that has not been tested much. feel free to give feedback
https://github.com/thomasgeissl/ESP-NOW-MIDI/blob/main/examples/dongle/dongle.ino#L123

**Comment by jhsa** [comment]
> on the client side, any midi message on any channel is fine to register at the dongle.
> i usually send cc channel 16, controller 127, value 127.

I meant, can I send any other message that isn't a midi message, just to activate the connection? The reason is, on my project, it could be that the first message comes from the dongle side. then this messages would be skipped because the connection is not yet active.
Also sending a random CC message is no good, because one fine day might read that message on that channel, and bad things could happen :) In my humble opinion, the best would be to send a non midi message, even if just a character.
Thanks.

**Comment by jhsa** [comment]
This is what I am doing:

https://www.youtube.com/watch?v=QKdMuJKQMsg

**Comment by thomasgeissl** [comment]
the history is mainly used for the midi monitor, which only makes sense if you connect a display.
i am using these: https://www.waveshare.com/wiki/0.96inch_OLED_Module
it is quite handy to use the dongle as a midi monitor


the dongle should have a function addPeer(mac), which i thought i had, but turns out, i do not
something like this. so you could add peers if you know their mac address

taken from the onDataRecv callback
```
  if (!peerExists && peerCount < DONGLE_MAX_PEERS) {
    memcpy(peerMacAddresses[peerCount], mac, 6);
    //regiester peer
    esp_now_peer_info_t peerInfo = {};
    memcpy(peerInfo.peer_addr, peerMacAddresses[peerCount], 6);
    peerInfo.channel = 0;      // Use the default Wi-Fi channel
    peerInfo.encrypt = false;  // Use unencrypted communication, or change as needed

    esp_err_t result = esp_now_add_peer(&peerInfo);
    if (result == ESP_OK) {
      Serial.println("Peer added successfully.");
    } else {
      Serial.print("Failed to add peer, error: ");
      Serial.println(result);
    }
    peerCount++;
  }
```

**Comment by thomasgeissl** [comment]
you could implement some broadcast logic on the receiver side, so it forwards all incoming messaes to every connected peer, expect the one who sent it.

or if you know the mac address from the peers, send it directly to them, without going via the dongle

**Comment by jhsa** [comment]
I am very new to programming and to ESP-NOW Thomas, that sounds great but I wouldn't even know how to start. Is there any example that shows something similar. I like that first idea of forwarding to all Peers except the one it was received from.
I don't really want to mess with the MAC numbers because I prefer to have all peers connecting to only one central server. Sending from one peer to another could even create some midi feedback loop, and that wouldn't be good at all..
Thank you. I am trying to put the ESP32-S2 inside an enclosure so I can test it tomorrow with the band. I know, living dangerously :P :D :)

**Comment by thomasgeissl** [comment]
probably something like this on the dongles ondatareceive function could work

```
  for (int i = 0; i < peerCount; i++) {
    // Skip the sender
    if (memcmp(peerMacAddresses[i], messageInfo->src_addr, 6) != 0) {
      esp_err_t result = esp_now_send(peerMacAddresses[i], incomingData, len);
      if (result != ESP_OK) {
        Serial.print("Failed to send to peer ");
        Serial.print(i);
      }
    }
  }
```

let me know how it goes with the enclosure, i havent had big issues with this, but obviously depends on distance and material.

**Comment by jhsa** [comment]
Thank you for all. I will test it live, and will report. as I said I want to update my uLoopino with the receiver code, and switching pedals. This one has a Display to configure the settings and the pedal Loops. The one I am using for now is based on a STM32 chip and it doesn't have wireless midi. The dongle will connect via serial midi to it. The next one will have both in one device :) The only thing we must take care with the ESP32 boards, is that they inject noise back into the power supply. :(

**Comment by jhsa** [comment]
> probably something like this on the dongles ondatareceive function could work
> 
> ```
>   for (int i = 0; i < peerCount; i++) {
>     // Skip the sender
>     if (memcmp(peerMacAddresses[i], messageInfo->src_addr, 6) != 0) {
>       esp_err_t result = esp_now_send(peerMacAddresses[i], incomingData, len);
>       if (result != ESP_OK) {
>         Serial.print("Failed to send to peer ");
>         Serial.print(i);
>       }
>     }
>   }
> ```
> 
> let me know how it goes with the enclosure, i havent had big issues with this, but obviously depends on distance and material.

Hi Thomas where would I place this in the function? At the end?  Or before:

```
 memcpy(&message, incomingData, sizeof(message));
  addToHistory(message);

  auto status = message.status;
  auto channel = message.channel;
  switch (status) {
```

Thanks

**Comment by thomasgeissl** [comment]
depends, if you wanna prioritise the broadcast over the usb midi, then put it at the beginning of the on data receive function. 
if you wanna prioritise usb midi, then put it at the end, after the switch block

**Comment by jhsa** [comment]
Cool, what would be the delay if I put it at the end? I will try this live today. Pictures tomorrow. No time today :)

**Comment by thomasgeissl** [comment]
usb midi should be quite fast, but i have never done benchmarks.
i dont think there will be a notable delay. 
i would assume this also depends on the host
but if i understood correctly you will be using the library to control your effect pedal. so this should not be so time critical. a couple ms more should not be a big deal i guess. i dont think it is that much to be honest.

optimizing the lib is also on the todo list.
also abstracting some of the dongle functionality away into its own class, so people like you with special needs, can use that class and extend it with custom features

**Comment by thomasgeissl** [comment]
@jhsa btw, i was working on a fix for version 3.3.0.
it is still untested, but in case you have some capacity, you could give it a try already.
should be hopefully fixed in way that it works with both version

https://github.com/thomasgeissl/ESP-NOW-MIDI/tree/fix/3.3.0_new_signature

**Comment by jhsa** [comment]
I will Thomas. Thank you. I still have the breadboard here near my PC. But only in a couple days as I am extremely busy this week. My gig on Saturday was canceled due to the weather. We did all come to my house and played music on in my living room :) The ESP-NOW MIDI worked really well.
This week will be a big test for it. My Sound mixer is controlled via WiFi, I have two in ear monitors that work on 2.4Ghz. On top of that, ESP-NOW works also on 2.4Ghz. This is going to be interesting ;) :D
Will let you know.

**Comment by thomasgeissl** [comment]
i am using the fix for 3.3.0 already, i think it is stable. 
but needs some cleanup, so i am able to register a custom send callback. or at least i should be able to mute the logging.

and i am afraid i broke older versions. i havent had time to test if the new library is compatible with the core < 3.3.0.

yes, i am currently running a project where i have 6 senders and 1 receiver. each sender sends on a different midi channel, no issues so far.

**Comment by jhsa** [comment]
Here I share the project I have been working on. It is meant for an ESp32-S2. It can be configured as Server or Client using the WiFi Manager library. 
To find out the Server MAC number, connect it to a serial monitor, then copy it and paste it in the client's MAC configuration field. Then save it and restart. 
We can have multiple Clients connected to the server, then all will share Midi data with all the others, except itself.
For USB Midi (Not USB Host) connect the ESP32-S2 to a computer or mobile device via USB. 
For serial Midi you need to add some MIDI circuit. The pins for serial midi are:
Midi_RX_Pin 1
Midi_TX_Pin 2

The code can for sure be improved. It seems to be working though.
To start the device in configuration mode, power it on while pressing the button. Then  connect via wifi to "ESP_NOW-MIDI Config"
Open your browser and insert http://192.168.4.1/ in the address field.
The configuration APP will start. 
Click on "Configure WiFi"

Now you can select the "Mode", and if 0 (Client) is selected, just paste the Server's MAC number in the MAC number field, then click "Save"
Reboot the device.

Please, feel free to improve the code and share it..

[ESP_NOW_USB_Serial_RX_17_Clean.zip](https://github.com/user-attachments/files/22130174/ESP_NOW_USB_Serial_RX_17_Clean.zip)

**Comment by thomasgeissl** [comment]
hey hey, i am going to close this issue, i am in the process of cleaning up and getting things ready.
feel free to open another one, if you run into other bugs. or have some feature requests.
the library lately improved quite a bit.
i am going to add support for midi host solutions, an s3 should be able to do that. din/trs midi should be much easier to handle. ideally i could expose these features via the the enomik sysex api, so one can configure it via
https://grantler-instruments.github.io/enomik-app/#/configurator

i am going to have a look at the snippets you provided, but i think i am sticking with my sysex configuration.
